### ISSUE TITLE
这个支持分类模型吗 

### ISSUE THREAD

**Issue by xxllp** [4paradigm/AutoX#1]

**Comment by poteman** [comment]
项目的目标是支持二分类、多分类以及回归。目前仅支持回归，支持二分类的版本在2021年8月15日之前推出。

**Comment by xxllp** [comment]
> 项目的目标是支持二分类、多分类以及回归。目前仅支持回归，支持二分类的版本预计在2021年8月15日之前推出。

哦 意思是还没有完全开源是吧 这个支持简单的 nn相关的模型吗

**Comment by poteman** [comment]
是的，目前这个项目还在完善中，后期会有支持nn相关的模型。

**Comment by xxllp** [comment]
这个跟你们公司内部用的automl 工具产品 是否没啥关系

**Comment by poteman** [comment]
公司内部的automl工具产品会有很多依赖，不适合直接开源。不过这个项目中会有很多和公司automl产品类似的策略，目前这个项目还在开发完善中，预计年底会有一个比较正式的版本。
