### ISSUE TITLE
task1_baseline.ipynb

### ISSUE THREAD

**Issue by Torres9999** [4paradigm/AutoX#29]
您是把一条数据中的实体拆分了吗？
一条数据对应一个实体？对应一个情感？

**Comment by DHengW** [comment]
一条数据里面有一段文本（T），多个实体（a,b,c)。每个实体在同一段文本里对应不同的情感级别(1,2,3)，所以把这一条数据拆成三条，形如 (T-a-1, T-b-2, T-c-3)
