### ISSUE TITLE
sohu baseline 的 DeBERTa不是还没中文版的吗，貌似效果很差

### ISSUE THREAD

**Issue by ioslide** [4paradigm/AutoX#30]
https://github.com/4paradigm/AutoX/blob/master/competition_baseline/biendata_sohu_2022/task1_baseline.ipynb

**Comment by DHengW** [comment]
huggingface上提供了上万个预训练模型，其中 https://huggingface.co/WENGSYX/Deberta-Chinese-Large 就是中文版，如果仍然不满足预期，可以尝试其他的预训练模型

**Comment by DHengW** [comment]
huggingface上提供了上万个预训练模型，其中 https://huggingface.co/WENGSYX/Deberta-Chinese-Large 就是中文版，如果仍然不满足预期，可以尝试其他的预训练模型

**Comment by ioslide** [comment]
> huggingface上提供了上万个预训练模型，其中 https://huggingface.co/WENGSYX/Deberta-Chinese-Large 就是中文版，如果仍然不满足预期，可以尝试其他的预训练模型

示例代码里用的是微软的那个版本 [捂脸] ,  谢谢了！
